uint8 mode
geometry_msgs/Pose2D goal
---
string result
nav_msgs/Odometry final_pos
int8 error_type
string error_message
---
string current_status
nav_msgs/Odometry current_pos
int16 distance_to_goal
int8 warning_type
string warning_message